### PR TITLE
Add support for quilt format and other compression methods

### PR DESCRIPTION
**Pull request by yegorich**
This patch is based on PR #32. In addition it supports both
diff formats:

*.diff.gz
*.debian.tar.{gz,bz2,xz,lzma}

### CODE REVIEW

**Comment by yegorich** [comment]
This PR also replaces https://github.com/freight-team/freight/pull/48.

**Comment by yegorich** [comment]
@mmoll, @mattock, @sjoerdmullender, @dpslavov could you please take a look at this PR? I have tested it with both `tar.gz` and `tar.xz` in the same folder.

**Comment by mattock** [comment]
This makes my brain and eys hurt :smile:. It is probably ok, but without testing I would not know. Are these changes covered by [our test suite](https://github.com/freight-team/freight/tree/master/test)? If tests show that this introduces no regressions then I'd be perfectly fine with merging this.

**Comment by yegorich** [comment]
@mattock the tests are not there because I have some issues with running them. See #101. A Docker image file would be great, so you can run the tests in a clean environment with all required dependencies.

**Comment by sjoerdmullender** [comment]
I have tried out this patch for a software release on all current Debian and Ubuntu systems, and it seems to have worked.
Also, looking at the code, the patch looks ok to me.

**Pull request merged**
