### PR TITLE
Debianized sources.

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
@dozzie @pulina I took the liberty of just cherry-picking this, I hope this is OK...
@mattock Could you have a look at this?

**Comment by dozzie** [comment]
Sure, no problem on my side.

**Comment by mattock** [comment]
Is the purpose of this PR to add support for creating Debian source packages for Freight?

I applied this PR and tested build on Debian 9. There was one warning:

```
$ dpkg-buildpackage -uc -us -b
--- snip ---
dpkg-gencontrol: warning: Depends field of package freight: unknown substitution variable ${shlibs:Depends}
--- snip ---
```
That seems harmless as the "binary" package gets generated regardless. But if we can fix this we should. The other similar macro, `${misc:Depends}`, seem to get added to freight.substvars:
```
$ cat debian/freight.substvars
misc:Depends=
misc:Pre-Depends=
```
Any ideas what is going on here?

Also, building a source package does not seem to work:

```
$ dpkg-buildpackage -uc -us -S
--- snip ---
 dpkg-source -b freight
dpkg-source: error: can't build with source format '3.0 (native)': native package version may not have a revision
dpkg-buildpackage: error: dpkg-source -b freight gave error exit status 255
```
If I change the source format to "3.0 (quilt)" (see [here](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#sourcef)) it seems to work better:

```
$ dpkg-buildpackage -uc -us -S
--- snip ---
 dpkg-source -b freight
dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../freight_0.3.11.orig.tar.{bz2,gz,lzma,xz}
dpkg-buildpackage: error: dpkg-source -b freight gave error exit status 255
```
Here it is at least looking for an "upstream" tarball.

**Comment by mmoll** [comment]
@mattock which dpkg version are you using? It seems to work fine with 1.19.0.5+b1 (coming with current Debian/testing)...

**Comment by mmoll** [comment]
@mattock allright, I'll have a look at this in some weeks... Let's not block the next release on this.

**Pull request closed without merging**
