### PR TITLE
Do not remove empty fields from control file and calculate size correctly

### PR DESCRIPTION
**Pull request by josegonzalez**
Copy of https://github.com/AtnNn/freight/commit/8c86e7b43032b7843def2e9616639529a1969e10

### CODE REVIEW

**Comment by mmoll** [comment]
Thanks @josegonzalez and @danielmewes for brining this here!
Some points:
- It would be nice to know who the original author was (@AtnNn?) so it can get recorded correctly as the author of this commit.
- what's the original issue fixed by this commit (some apt problems, incorrect sizes?)?
- shellcheck is reporting a problem, hence the failing Travis tests
- a BATS test to check the correct behaviour would be nice

**Comment by josegonzalez** [comment]
That is correct, @AtnNn was the original author (following the trail of commits anyhow).

**Comment by AtnNn** [comment]
I did write this code. I forget what removed field had caused problems. I added support for symlinks because our repo was managed by git-annex, which replaces all files with a symlink, which freight otherwise seemed to handle correctly, but reported their size as 0.

**Comment by mmoll** [comment]
any movement here? at least shellcheck and the tests should pass...

**Comment by josegonzalez** [comment]
The rethinkdb people will need to update the code since I'm not in their repo...

**Comment by mmoll** [comment]
shellcheck is still reporting a problem, also if this could get rebased onto curent master and the change could get boiled down to one commit it would be nice...

**Comment by mmoll** [comment]
see #64 for pulling in the first change and https://github.com/rcrowley/freight/issues/53 for the reasoning of strpping out empty fields

**Pull request closed without merging**
