### PR TITLE
Support gpg2 in freight cache passphrase file option

### PR DESCRIPTION
**Pull request by hnakamur**
Please see https://wiki.archlinux.org/index.php/GnuPG#Unattended_passphrase for gpg's `--pinentry loopback` option.

### CODE REVIEW

**Comment by mmoll** [comment]
@hnakamur Could you reformat the code according to the shfmt output in the tests?
@mattock Could you have a look? I guess that would solve GH-72 more completely then what we have now.

**Comment by hnakamur** [comment]
@mmoll Could you tell me more detailed explanation about the code format?
I had followed the format of the code [lib/freight/apt.sh#L212-L228](https://github.com/freight-team/freight/blob/92dc0e2f43b751340ce6c7031f4e4612ed36c9fb/lib/freight/apt.sh#L212-L228).
There were redundant backslashes ` \` after `&&`, so I removed them and push a new commit d05b107.

**Comment by hnakamur** [comment]
Ah, I looked at the result of Travis CI and got it! I'm fixing it now.

**Comment by mattock** [comment]
Sorry for the delay in reviewing this. The check for `--pinentry-mode loopback` is a really nice one. I tested this PR with Ubuntu 16.04 / GnuPG 1.4.20 and automatic retrieval of the GnuPG passphrase from a file worked fine.

I was able to reproduce my [original GnuPG 2.x problem](https://github.com/freight-team/freight/issues/72) by removing pinentry-curses package and by using the current freight version in our apt repositories (0.3.11). When I installed freight with this patch applied the problem went away.

Consider this an ACK/approval of this PR :+1:

**Comment by mmoll** [comment]
merged, thanks @hnakamur!

**Pull request merged**
