### PR TITLE
Add changelog for 0.3.13

### PR DESCRIPTION
**Pull request by mattock**

### CODE REVIEW

**Comment by mattock** [comment]
As discussed in the ddeb PR I want to release a new freight package. So I assume it is ok to merge this and get it done with :smile:.

**Comment by yegorich** [comment]
@mattock when are you going make a release and what other PRs should go in?

**Comment by mattock** [comment]
I pushed out the release to the apt repos already. But if there are other PRs that can be merged soon I can easily push out another release.

**Comment by yegorich** [comment]
I'd like to have this [one](https://github.com/freight-team/freight/pull/100) merged or at least reviewed.

**Pull request merged**
