### PR TITLE
Look for correct extension to tar and diff files.

### PR DESCRIPTION
**Pull request by sjoerdmullender**
This refers to issue #24.

### CODE REVIEW

**Comment by client9** [comment]
cool, we need to update the `freight-add` man page.

```
freight-add registers package with one or more manager/distro[/component] pairs (or triples). Currently, apt is the only supported manager and package must be one of *.deb, *.dsc *.debian.tar.gz *.orig.tar.gz, *.dsc *.diff.gz *.orig.tar.gz, or *.dsc *.tar.gz.
```

**Comment by mmoll** [comment]
I didn't test this, yet... I'm not unwilling to merge this, if this works, but it would be really nice to have this also BATS tested then.

**Comment by mmoll** [comment]
leaving #40 open for later

**Comment by haus** [comment]
It looks like with this PR package_version.debian.tar.{gz,bz2,xz} files are no longer recognized as being part of a source download, which breaks source generation for some build outputs.

**Comment by haus** [comment]
https://debian-handbook.info/browse/stable/sect.source-package-structure.html has more details on it, but alongside an orig.tar.gz and dsc file there can be either a gzipped diff (diff.gz) or an archive of the debian directory (debian.tar.{gz,bz2,xz}).

**Comment by melissa** [comment]
I have confirmed that downgrading to 0.3.8 correctly includes sources and correctly generates build output that includes those files

**Comment by mmoll** [comment]
I'll revert this.

**Comment by mmoll** [comment]
@mattock please build 0.3.10 into the apt repo - that's 0.3.9 with this change reverted

**Comment by haus** [comment]
thanks @mmoll !

**Comment by melissa** [comment]
Thank you!

**Comment by mmoll** [comment]
very sorry for the breakage :(

**Comment by melissa** [comment]
When can we expect the 0.3.10 packages to be available?

**Comment by mattock** [comment]
Freight 0.3.10 package is now available in freight's apt repository.

**Pull request closed without merging**
