### PR TITLE
Change tabs to spaces, add vim modelines

### PR DESCRIPTION
**Pull request by domcleal**
I'm trying not to bikeshed, only trying to improve consistency.

### CODE REVIEW

**Comment by mattock** [comment]
I agree we should remain consistent. I personally prefer spaces, but if the majority of the codebase uses tabs, then let's use those for now.

**Comment by mmoll** [comment]
Personally I prefer spaces and two space indentation (Ruby style). so if we all could agree on spaces, and even better on the count, we could just have one `:retab` commit and use this in the future.

If we want to stay with hard tabs and four space "display expansion" I also have no problem with it. :)

**Comment by domcleal** [comment]
I don't much care as long as my editor takes care of it, happy to go with either.  Tabs might be slightly easier if we're considering merging any patches back from rcrowley/freight or its PRs, but that's the only argument I can see for it.

**Comment by mattock** [comment]
I prefer 4 spaces :). However, I can live with 2 just fine, and would prefer that to tabs.

**Comment by mmoll** [comment]
so, spaces it wil be... @domcleal you are the one to choose between 2 and 4 then :)

**Comment by domcleal** [comment]
I walked into that one, didn't I?  I opted for four spaces as that's what I'm more accustomed to seeing in shell scripts.  Commits are updated to use expanded tabs in modelines and then change all tabs to four spaces.

**Comment by mmoll** [comment]
:+1:

**Comment by mmoll** [comment]
merged, thanks @domcleal!

**Pull request merged**
