### PR TITLE
Error messages suppressing and support bz2 orig files.

### PR DESCRIPTION
**Pull request by dpslavov**
1. Suppress error messages when link can't be created and files will be copied instead.
2. Support bz2 compressed orig files.

### CODE REVIEW

**Comment by mmoll** [comment]
The first commit can IMHO go in, not sure about the second after the stirup we saw with #32

**Comment by mmoll** [comment]
I cherry-picked the first commit into master.

**Comment by miroR** [comment]
@mmoll wrote:
> not sure about the second after the stirup we saw with #32

(I'll try and carefully study the stirrup... not that I can do much) ...but **_bz2 orig_** files appear to not be supported. Pls. see my post at:
https://github.com/freight-team/freight/issues/24#issuecomment-377475265

So which issue does my problems go? To #24 or here in #48 ? And accordingly where do I post more info if I do conquer some more understanding?

**Comment by mmoll** [comment]
this needs a rebase now :)

**Comment by yegorich** [comment]
Closed in favour of #100

**Pull request closed without merging**
