### PR TITLE
Patches from uwabami/freight

### PR DESCRIPTION
**Pull request by mattock**
These two useful patches from uwabami/freight have not yet been merged. They look good to me, but somebody else might want to review them also.

### CODE REVIEW

**Comment by domcleal** [comment]
:+1: look fine to me also.  I'd merge, but I don't have permission - you may need to add the freight-team members team under the repo settings with write permissions.

**Comment by mmoll** [comment]
Per https://wiki.debian.org/Projects/DebSrc3.0 also .tar.lzma would need to get added.

**Comment by mattock** [comment]
@domcleal: Yeah, sure, I can grant you and others the necessary permissions. I think we should first set some general guidelines for ourselves first. Here are my suggestions:
* Always use pull requests, so that:
 * Each change can be reviewed before merging it to "master"
 * Travis can test each PR (we'd need .travis.yaml first, of course)
* Require somebody else to review and accept ("ACK") a PR before it is merged

Does this sound reasonable to you guys?

@mmoll: good catch! I'm not sure if it is required, but lzma support should be there anyways.

@uwabami: could you add .lzma support and issue a PR?

**Comment by domcleal** [comment]
@mattock yes, agreed entirely

**Comment by mattock** [comment]
I will merge this pull request. Lzma support can be added later in a separate pull request. @domcleal: I will grant you merge permissions. What about @mmoll, @uwabami: do you want/need more permissions?

**Comment by domcleal** [comment]
Thanks @mattock.  I'd certainly second @mmoll if he's interested, we both run Freight and packaging in the Foreman project.

**Comment by mattock** [comment]
Ah, nice! I run freight for OpenVPN and happen to use Puppet extensively. I can provide an apt repository for freight packages on one of our webservers.

**Pull request merged**
